% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Initial observations on the Myanmar Food Security Cluster 5Ws}
\author{Sean Ng}
\date{04/02/2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Initial observations on the Myanmar Food Security Cluster 5Ws},
  pdfauthor={Sean Ng},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

{
\setcounter{tocdepth}{4}
\tableofcontents
}
\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

This report is an overview of the initial observations and analysis
performed on the Food Security Cluster 5Ws data for 2021; the issues
identified and analysis have been broken into large groups corresponding
with the first 4 chapters -- geographical coverage, activities and
modalities, partners and beneficiaries. This report ends with a brief
section on next steps and an interactive reference table and interactive
reference maps.

The FSC has endeavoured to provide actionable information and believe
that releasing this report is a necessary part of jump-starting the
process of resolving the more pressing concerns identified. Further
analysis is merited in several areas; and this will be undertaken once
consultations with partners have been completed. Unless otherwise
specified, beneficiary figures in this report are unique beneficiaries,
as opposed to beneficiary frequencies.

\hypertarget{a.-summary-of-key-findings}{%
\subsubsection{a. Summary of key
findings}\label{a.-summary-of-key-findings}}

\begin{itemize}
\item
  The 2021 response was \textbf{skewed towards very few areas} -- Yangon
  and Rakhine form 78\% of the beneficiaries reached, with 24\% of all
  beneficiaries originate from Hlaingtharya township alone. The top 10
  townships account for 76\% of all beneficiaries reached.
\item
  Four of the eight Food Security activities (monthly food baskets,
  support for income generation, livestock kits and fishery kits)
  experienced \textbf{large ramp ups} in beneficiaries reached after the
  addition of the 2021 HRP addendum; but the caseloads for the provision
  of cash-based transfers and technical training were largely
  established prior to 2021 and only saw incremental increases in
  beneficiaries reached throughout the year.
\item
  \textbf{61\%} of beneficiary frequencies received support through the
  in-kind delivery modality; \textbf{25\%} of beneficiary frequencies
  were reached by cash transfers -- of beneficiaries who received cash
  transfers, 84\% of them were reached through direct cash payments.
\item
  The most common transfer values -- in terms of beneficiaries reached
  -- are \textbf{between USD 60 and 80} per month per household, it
  should also be noted that a not insignificant number of households
  (about 8\%) were reached by cash transfer interventions valued at USD
  100 per household or more. The highest average cash transfers were
  from the provision of livestock kits and the lowest averages from Cash
  for work/food for assets activities.
\item
  Around 60\% of beneficiary households have received 50\% or more of
  the \textbf{Minimum Expenditure Basket (MEB)} for food for the months
  they were covered. However, about 10\% of all beneficiary households
  for monthly cash-based transfers received under USD 20 per month (less
  than 10\% of the MEB) and 23\% of households received between USD 20
  and USD 40 (22\% of the MEB).
\item
  A total of 66 unique partners reported in the 5Ws during 2021. Of the
  partners who reported in the 5Ws, \textbf{62 were implementing
  partners}; 27 partners classified themselves as reporting
  organisations, though 23 of these were also implementing partners.
\item
  \textbf{Only 13 implementing partners (78\% of the total) have a
  presence in more than 5 townships}, and only 8 have a presence in more
  than 10. 34 implementing partners have reached less than 10,000
  beneficiaries in 2021 and the median number of beneficiaries reached
  in this period by implementing partners is 6,118.
\item
  \textbf{Age and sex-disaggregated beneficiary figures} are one of the
  most key pieces of missing data in the 5W dataset; values have been
  largely backfilled from census data and do not provide an accurate
  representation of the population reached.
\item
  \textbf{82.68\% of beneficiaries are from the host/local community},
  9.02\% are stateless persons from Rakhine and 8.24\% are IDPs.
  Returnees are the rarest type of beneficiary reached, forming only
  0.07\% of all beneficiaries reached.
\item
  49\% of beneficiaries of monthly activities experienced \textbf{gaps
  or delays in monthly programming}, with the most common delay being 3
  months. Gaps in monthly programming were experienced in 39 townships,
  with the majority orginating from Kachin, Ayeyarwady and Rakhine.
\item
  Food Security Cluster partners are \textbf{not well-positioned to
  cover the 2022 population in need}. Partners are largely concentrated
  in Kachin, Rakhine and Yangon, with only one partner present in Shan
  (East) and two in Tanintharyi. Overall, 58\% of townships, containing
  46\% of the 2022 PIN, do not have any partners present.
\end{itemize}

\hypertarget{b.-achievements-related-to-the-hrp-and-ierp}{%
\subsubsection{b. Achievements related to the HRP and
IERP}\label{b.-achievements-related-to-the-hrp-and-ierp}}

Though this document is not intended to report on or focus on solely
HRP-related activities -- it is important to analyse the entirety of all
Food Security activities reported in 2021 -- this preliminary section
contains a brief summary of Humanitarian Response Plan (HRP) and HRP
addendum-related achievements. In 2021, 21.51\% of reached beneficiaries
were related to the original HRP and 63.91\% were related to the HRP
addendum (IERP):

\begin{table}

\caption{\label{tab:hrp-version-table}Beneficiaries, townships and implementing partners by HRP, HRP addendum and non-HRP activities}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
hrp\_version & townships & implementing\_partners & beneficiaries & pc\_of\_ben & target\_2021 & pc\_of\_target\\
\hline
hrp & 38 & 32 & 701,339 & 21.51 & 601,235 & 116.65\\
\hline
ierp & 102 & 39 & 2,084,185 & 63.91 & 2,167,114 & 96.17\\
\hline
non\_hrp & 49 & 21 & 475,444 & 14.58 &  & \\
\hline
total & 151 & 62 & 3,260,968 & 100.00 & 2,768,349 & 100.62\\
\hline
\multicolumn{7}{l}{\rule{0pt}{1em}'pc\_of\_target' only takes into account the 2,785,524 HRP and IERP beneficiaries}\\
\end{tabular}
\end{table}

The provision of monthly food baskets was the single largest activity,
forming 84.09\% of all reached beneficiaries. This was followed by the
provision of monthly cash-based transfers and the provision of crop and
vegetable kits.

\begin{table}

\caption{\label{tab:barplot-hrp-ierp-activities}Beneficiaries reached by HRP indicator and activity}
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
HRP\_indicator/activity & HRP & IERP & total\_HRP\_IERP & pc\_of\_total\\
\hline
1.Number of people who received food and/or cash assistance & 529,584 & 2,033,565 & 2,563,149 & 92.02\\
\hline
2.Number of people who received agriculture and other livelihood support & 171,755 & 50,620 & 222,375 & 7.98\\
\hline
Provide monthly food baskets & 313,187 & 2,029,282 & 2,342,469 & 84.09\\
\hline
Provide monthly cash-based transfers & 216,397 & 4,283 & 220,680 & 7.92\\
\hline
Provide crops \& vegetables kits & 99,028 & 10,820 & 109,848 & 3.94\\
\hline
Provide support for income generation & 48,245 & 1,565 & 49,810 & 1.79\\
\hline
Cash for Work / Food for Assets & 15,615 & 25,653 & 41,268 & 1.48\\
\hline
Provide technical training & 3,074 & 6,672 & 9,746 & 0.35\\
\hline
Provide fishery kits & 643 & 5,194 & 5,837 & 0.21\\
\hline
Provide livestock kits & 5,150 & 716 & 5,866 & 0.21\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}non-HRP beneficiaries have been excluded}\\
\end{tabular}
\end{table}

As a note, less than 7\% of all beneficiaries reached were associated
with COVID-19 response activities, perhaps indicating that COVID-related
activities have been largely mainstreamed.

\begin{table}

\caption{\label{tab:unnamed-chunk-2}COVID-19 response by HRP version}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
covid\_19\_response & IERP & HRP & non\_HRP & total\_ben & pc\_of\_total\\
\hline
Yes & 68,409 & 57,429 & 98,777 & 224,615 & 6.89\\
\hline
No & 2,015,776 & 643,910 & 376,667 & 3,036,353 & 93.11\\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}All beneficiaries have been included in 'total\_ben'}\\
\end{tabular}
\end{table}

\hypertarget{geographical-coverage}{%
\subsection{1. Geographical coverage}\label{geographical-coverage}}

\hypertarget{comparing-beneficiaries-reached-and-2021-pin-by-state-and-region}{%
\subsubsection{1.1 Comparing beneficiaries reached and 2021 PIN by state
and
region}\label{comparing-beneficiaries-reached-and-2021-pin-by-state-and-region}}

A total of 3,260,968 unique beneficiaries have been reached across the
country, of which, 2,785,524 pertained to HRP and IERP activities and
townships and 475,444 were non-HRP. Overall, 100.62\% of the targeted
2,768,349 persons in the HRP/IERP were reached.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/barplot-state-beneficiaries-pin-1.pdf}

\hypertarget{table-of-beneficiaries-and-pin-by-state-and-region}{%
\subsubsection{1.2 Table of beneficiaries and PIN by state and
region}\label{table-of-beneficiaries-and-pin-by-state-and-region}}

\begin{table}

\caption{\label{tab:table-beneficiaries-pin-state}Beneficiaries reached (desc.) by state/region}
\centering
\begin{tabular}[t]{l|r|r|r|r|>{}r}
\hline
state & HRP\_ben & IERP\_ben & non\_HRP\_ben & total\_ben & \%\_of\_total\_ben\\
\hline
Yangon & 0 & 1,828,932 & 182,643 & 2,011,575 & \cellcolor[HTML]{440154}{\textcolor{white}{61.69}}\\
\hline
Rakhine & 530,202 & 0 & 0 & 530,202 & \cellcolor[HTML]{21A585}{\textcolor{white}{16.26}}\\
\hline
Mandalay & 0 & 25,037 & 118,489 & 143,526 & \cellcolor[HTML]{59C864}{\textcolor{white}{4.40}}\\
\hline
Ayeyarwady & 0 & 66,432 & 33,049 & 99,481 & \cellcolor[HTML]{62CB5F}{\textcolor{white}{3.05}}\\
\hline
Magway & 0 & 7,645 & 89,122 & 96,767 & \cellcolor[HTML]{64CB5F}{\textcolor{white}{2.97}}\\
\hline
Kachin & 89,818 & 0 & 0 & 89,818 & \cellcolor[HTML]{65CB5E}{\textcolor{white}{2.75}}\\
\hline
Shan (North) & 53,733 & 4,954 & 14,416 & 73,103 & \cellcolor[HTML]{69CD5B}{\textcolor{white}{2.24}}\\
\hline
Kayin & 13,503 & 47,338 & 7,267 & 68,108 & \cellcolor[HTML]{69CD5B}{\textcolor{white}{2.09}}\\
\hline
Mon & 0 & 41,383 & 6,798 & 48,181 & \cellcolor[HTML]{6ECE58}{\textcolor{white}{1.48}}\\
\hline
Sagaing & 0 & 27,992 & 3,993 & 31,985 & \cellcolor[HTML]{72D056}{\textcolor{white}{0.98}}\\
\hline
Kayah & 0 & 16,457 & 1,289 & 17,746 & \cellcolor[HTML]{76D054}{\textcolor{white}{0.54}}\\
\hline
Chin & 9,726 & 7,279 & 0 & 17,005 & \cellcolor[HTML]{76D054}{\textcolor{white}{0.52}}\\
\hline
Shan (South) & 0 & 5,750 & 9,761 & 15,511 & \cellcolor[HTML]{76D054}{\textcolor{white}{0.48}}\\
\hline
Bago (East) & 4,357 & 0 & 8,617 & 12,974 & \cellcolor[HTML]{76D054}{\textcolor{white}{0.40}}\\
\hline
Tanintharyi & 0 & 4,476 & 0 & 4,476 & \cellcolor[HTML]{7AD151}{\textcolor{white}{0.14}}\\
\hline
Shan (East) & 0 & 510 & 0 & 510 & \cellcolor[HTML]{7AD151}{\textcolor{white}{0.02}}\\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}All beneficiaries have been included in this table, regardless of their inclusion in the HRP/IERP}\\
\end{tabular}
\end{table}

The response is fairly skewed at the state/region level. Yangon and
Rakhine form 78\% of the beneficiaries reached. Beneficiaries from
Rakhine were mostly associated with the HRP, whilst beneficiaries from
Yangon were mostly associated with the IERP.

\hypertarget{township-level-distribution-of-beneficiaries}{%
\subsubsection{1.3 Township-level distribution of
beneficiaries}\label{township-level-distribution-of-beneficiaries}}

Just as the response is heavily weighted towards Yangon and Rakhine at
the state and region level, the same is also true at the township level.
These 10 townships below are where 76\% of all FSC beneficiaries.

\begin{table}

\caption{\label{tab:table-top-townships-beneficiaries}Top 10 townships by beneficiaries reached (desc)}
\centering
\begin{tabular}[t]{l|l|r|r|r|>{}r|r}
\hline
state & township & HRP\_ben & IERP\_ben & non\_HRP\_ben & total\_ben & \%\_of\_total\_ben\\
\hline
Yangon & Hlaingtharya & 0 & 594,836 & 177,822 & \cellcolor[HTML]{440154}{\textcolor{white}{772,658}} & 23.69\\
\hline
 & Other 141 townships & 282,037 & 305,963 & 178,733 & \cellcolor[HTML]{450357}{\textcolor{white}{766,733}} & 23.51\\
\hline
Yangon & Shwepyithar & 0 & 379,774 & 776 & \cellcolor[HTML]{27808E}{\textcolor{white}{380,550}} & 11.67\\
\hline
Yangon & Dagon Myothit (Seikkan) & 0 & 276,430 & 0 & \cellcolor[HTML]{1E9B8A}{\textcolor{white}{276,430}} & 8.48\\
\hline
Yangon & Dala & 0 & 271,760 & 0 & \cellcolor[HTML]{1E9D89}{\textcolor{white}{271,760}} & 8.33\\
\hline
Yangon & North Okkalapa & 0 & 255,380 & 0 & \cellcolor[HTML]{1FA187}{\textcolor{white}{255,380}} & 7.83\\
\hline
Rakhine & Sittwe & 149,885 & 0 & 0 & \cellcolor[HTML]{3DBC74}{\textcolor{white}{149,885}} & 4.60\\
\hline
Rakhine & Buthidaung & 147,985 & 0 & 0 & \cellcolor[HTML]{3DBC74}{\textcolor{white}{147,985}} & 4.54\\
\hline
Rakhine & Maungdaw & 121,432 & 0 & 0 & \cellcolor[HTML]{4CC26C}{\textcolor{white}{121,432}} & 3.72\\
\hline
Mandalay & Nyaung-U & 0 & 0 & 71,547 & \cellcolor[HTML]{69CD5B}{\textcolor{white}{71,547}} & 2.19\\
\hline
Mandalay & Myingyan & 0 & 42 & 46,566 & \cellcolor[HTML]{7AD151}{\textcolor{white}{46,608}} & 1.43\\
\hline
\multicolumn{7}{l}{\rule{0pt}{1em}All beneficiaries have been included in 'total\_ben', regardless of their inclusion in the HRP/IERP}\\
\end{tabular}
\end{table}

151 townships overall have been reached by food security activities in
2021. This is 42.42\% the 330 townships in the country. 140 townships
have been reached by HRP/IERP activities.

It is important to note that the 2021 targets -- especially those for
the IERP -- were developed more of as an approximation of response
capacities rather than being estimates related to any measure of
vulnerability. Additionally, not all townships targeted as part o the
IERP have specific targets: for instance, neither Nyaung-U nor Myingyan
(both in Mandalay) from the table above had specific targets.

To momentarily narrow down the focus to the 55 townships with specific
HRP or IERP targets, there is substantial variance in the percentage of
the target that has been reached. Hlaingtharya's beneficiary figures are
378\% of its established target, whereas Hpapun in Kayin and Kyethi in
Shan had been targeted since the initial HRP and have not been reached
by any FSC activities; additionally, Dagon Myothit (North) and Insein in
Yangon and Chanayethazan in Mandalay were targeted in the IERP and also
have not been reached.

Of these 55 townships, 28 townships reached more than 120\% of their
target, 3 reached between 100\% and 119\% of their target; 4 townships
reached between 80\% and 100\% of their target; and 15 townships reached
less than 80\% of their target.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/histogram-beneficiaries-hrp-target-reached-1.pdf}

The histogram above groups townships based on the percent of their
target reached, with the percent reached on the x-axis and the number of
townships on the y-axis. From a programme management perspective, it
would be desirable to see the majority of townships within the yellow
box (between 80\% and 120\% of the target reached), which would indicate
the judicious deployment of resources. However, we see that both
overreach and under-reaching are very common, with the largest numbers
of townships clustered around 0\% and 200\% or more of the target
reached.

\hypertarget{locations}{%
\subsubsection{1.4 Locations}\label{locations}}

Partners have responded in a total of 2,494 locations across the
country, with the vast majority of locations only having only one
partner operating in them; the maximum number of partners in any
location is 4. Of the 16,041 rows reported in the 5Ws, only 211 did not
report a specific location.

Locations are classified into three groups -- camps, industrial zones
and villages/towns/wards:

\begin{table}

\caption{\label{tab:table-locations}Summary of location types}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
location\_type & locations & townships & beneficiaries & pc\_of\_ben & avg\_ben\\
\hline
village\_ward\_town & 2,083 & 125 & 2,546,522 & 88.45 & 1,223\\
\hline
camp & 435 & 42 & 324,606 & 11.27 & 746\\
\hline
industrial\_zone & 5 & 2 & 7,870 & 0.27 & 1,574\\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}381,970 beneficiaries were reported in the 211 rows without specific locations}\\
\end{tabular}
\end{table}

The vast majority of locations are served by only one partner. Below are
a series of histograms showing the variation in the number of
beneficiaries by location, split by number of partners in each location.
Locations with one partner present have a large peak around 100
beneficiaries per locations; and a slight majority of locations with two
partners have more than 1,000 beneficiaries.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/histogram-locations-by-partner-1.pdf}

In general, the more partners operating in a given location, the higher
the average number of beneficiaries; however, it should be noted that
these multi-partner locations are comparatively rare. The locations with
four partners are Nam Hlaing in Bhamo, where it is suspected that the
high number of partners is due to beneficiaries from this village
participating in a range of activities and trainings held in the
township seat, and Momauk Baptist Church, which is a camp location.

\begin{table}

\caption{\label{tab:table-locations-partners}Average beneficiary frequencies in locations with one, two, three and four partners}
\begin{tabular}[t]{l|r|r}
\hline
number\_of\_partners & locations & avg\_beneficiaries\\
\hline
one & 2,429 & 389\\
\hline
two & 206 & 3,973\\
\hline
three & 30 & 5,787\\
\hline
four & 2 & 13,154\\
\hline
\end{tabular}
\end{table}

When group by number of distinct FSC activities by location, it is
observed that a majority of locations had only one FSC activity being
implemented there. The spike in number of townships with 3 activities
per location were mostly villages and towns in Ayeyarwady and Magway.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/histogram-locations-by-activities-1.pdf}

As expected, the higher number of FSC activities in a given location,
the higher the number of beneficiary frequencies reached. The tow
locations with 5 activities being implemented in them are a camp in
Pauktaw and a village in Maungdaw. Once data from other Clusters is
obtained, multi-sector coverage and interactions between activities
should be explored.

\begin{table}

\caption{\label{tab:table-locations-activities}Average beneficiary frequencies in locations with one, two, three, four and five activities}
\begin{tabular}[t]{l|r|r}
\hline
number\_of\_activities & locations & avg\_beneficiary\_frequencies\\
\hline
one & 1,879 & 272\\
\hline
two & 368 & 552\\
\hline
three & 459 & 2,178\\
\hline
four & 22 & 2,972\\
\hline
five & 2 & 41,626\\
\hline
\end{tabular}
\end{table}

\hypertarget{activities-and-modalities}{%
\subsection{2. Activities and
modalities}\label{activities-and-modalities}}

\hypertarget{monthly-progress-by-activity}{%
\subsubsection{2.1 Monthly progress by
activity}\label{monthly-progress-by-activity}}

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/line-plot-facet-activity-1.pdf}

The plot above shows the FSC's achievements across the eight 5W
activities. The majority of the caseload for monthly cash-based
transfers was established prior to 2021 (with the number of
beneficiaries only increasing very incrementally across the course of
the year) -- this highlights that many of the projects contributing to
this activity repeat year after year and had been ongoing prior to the
HRP; this pattern is also seen in the provision of technical training.

One of the difficulties of interpreting these data is that it is not
always apparent where the patterns observed are reflective or changes in
the field (such as changes in access, funding or staffing) or if they
are instead due to partners' reporting behaviours. For instance, for the
large jump in the number of beneficiaries for fishery kits and food
baskets after June 2021 (marked by the dotted grey line), this coincides
with the approval of the HRP addendum/IERP. However, the reasons behind
some of the other changes are less clear and will require careful
exploration with partners.

\hypertarget{delivery-modalilties}{%
\subsubsection{2.2 Delivery modalilties}\label{delivery-modalilties}}

Cash and in-kind distributions were each the main delivery modality in
three activities, with the provision of services and support being
predominant in two. The in-kind modality has the highest reach, given
the especially large beneficiary numbers originating from the provision
of monthly food baskets. Several misclassifications -- small portions of
monthly cash transfers have been coded as ``in-kind'' and there are
in-kind food baskets coded as ``cash'' and ``hybrid''. It might also be
worth more clearly delineating between ``support for income-generating
activities'' and the ``provision of technical training'' as service
delivery and support are heavily present in both.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/barplot-facet-activity-modality-1.pdf}

61\% of beneficiary frequencies received support through the in-kind
service delivery; beneficiary frequencies are used here as there were
several instances of modalities changing partway through an
intervention: for reference, 83\% of beneficiaries were reached
initially with in-kind interventions, meaning that there was a tendency
to diversify away from in-kind support over the course of the year. 25\%
of beneficiary frequencies were reached through cash transfers.

\begin{table}

\caption{\label{tab:table-modality-frequency}Beneficiary frequencies by delivery modalities and frequency of distribution}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r|r}
\hline
delivery\_modality & First & Monthly & One-off & Other & NA & Total & \%Total\\
\hline
In-kind & 303,595 & 1,850,712 & 509,892 & 2,773,854 & 111,839 & 5,549,892 & 61.36\\
\hline
Cash & 894 & 1,923,133 & 176,464 & 40,274 & 117,525 & 2,258,290 & 24.97\\
\hline
Service delivery/support &  & 773,212 & 128,852 & 4,901 & 767 & 907,732 & 10.04\\
\hline
Hybrid (In-kind \& Cash) &  & 295,312 & 2,938 & 10,810 &  & 309,060 & 3.42\\
\hline
Voucher &  &  & 2,652 & 16,519 &  & 19,171 & 0.21\\
\hline
Total & 304,489 & 4,842,369 & 820,798 & 2,846,358 & 230,131 & 9,044,145 & 100.00\\
\hline
\multicolumn{8}{l}{\rule{0pt}{1em}Beneficiary frequencies reported without a delivery modality specified have been excluded}\\
\end{tabular}
\end{table}

Regarding the table above, there is a strong argument to remove the
option ``other'' from the 5W column \texttt{frequency} (referring to
frequency of transfer/delivery) -- what exactly it connotes is unclear,
as partners might elect this option for activities that occur both more
and less frequently than every month; there is also the possibility that
partners are just electing ``other'' instead of leaving the column
blank. It is possible to backfill some of the ``other'' values from the
\texttt{beneficiary\_recurrency} column. This will be explored further
in the chapter on beneficiaries.

There is also justification to drop the ``First'' category as it does
not really have much relation to the ``Monthly'' category, i.e.~an
increase in beneficiaries reported as ``First'' do not correspond to an
increase in ``Monthly'' beneficiaries in the following months, meaning
that these beneficiaries should fall under the ``One-off'' category.

The column \texttt{months\_of\_food\_ration\_distributed}, but this
column is largely blank and non-NA values have also not been filled
well, meaning that a key piece of data -- activity durations -- has not
been effectively captured. However, a workaround -- requiring
considerable effort -- yields us the table below, showing the average
duration (in months) of the various activities classified as ``Monthly''
under the \texttt{frequency} column:

\begin{table}

\caption{\label{tab:table-avg-duration-activities}Average duration (in months) of monthly activities}
\begin{tabular}[t]{l|r}
\hline
activity & avg\_duration\_months\\
\hline
Provide monthly cash-based transfers & 7.42\\
\hline
Provide crops \& vegetables kits & 6.00\\
\hline
Provide support for income generation & 5.99\\
\hline
Provide technical training & 4.75\\
\hline
Provide monthly food baskets & 4.27\\
\hline
Cash for Work / Food for Assets & 2.13\\
\hline
\multicolumn{2}{l}{\rule{0pt}{1em}Only 'monthly' activities included}\\
\end{tabular}
\end{table}

\hypertarget{monetary-values-of-intervention-packages-per-household}{%
\subsubsection{2.3 Monetary values of intervention packages per
household}\label{monetary-values-of-intervention-packages-per-household}}

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/plot-usd-hhd-bin-1.pdf}

The most common transfer values -- in terms of beneficiaries reached --
are between USD 60 and 80, it should also be noted that a not
insignificant number of households (about 8\%) were reached by cash
transfer interventions valued at USD 100 per household or more (though
to what extent the more extreme values are correct remains to be
investigated). It should also be noted that 35\% of the households who
received transfers values at below USD 40/month were the beneficiaries
of the ``hybrid'' delivery modality, and it is possible that the value
of the in-kind goods they received might not have been included in this
sum. Please note that these monetary values were calculated only from
unique beneficiary households and that these are not the cumulative sums
per household.

\begin{table}

\caption{\label{tab:table-usd-hhd-bin-frequency}Cash transfer, hybrid and voucher values per household, by cash delivery mechanism (USD)}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r}
\hline
cash\_delivery\_mechanism & <\$10 & >=\$10\_<\$20 & >=\$20\_<\$40 & >=\$40\_<\$60 & >=\$60\_<\$80 & >=\$80\_<\$100 & >=\$100 & total\_hhd & pc\_of\_hhd\\
\hline
Direct cash payment & 9,045 & 5,467 & 7,483 & 9,065 & 20,313 & 1,543 & 4,086 & 57,002 & 85.59\\
\hline
E-voucher &  &  & 2,519 &  & 929 &  &  & 3,448 & 5.18\\
\hline
E-transfer &  &  & 798 & 1,161 &  &  & 435 & 2,394 & 3.59\\
\hline
Mobile money &  & 1,830 &  &  &  &  &  & 1,830 & 2.75\\
\hline
Money Transfer Agent & 517 & 90 &  &  &  &  & 841 & 1,448 & 2.17\\
\hline
Other &  &  &  &  & 8 &  & 424 & 432 & 0.65\\
\hline
Paper voucher &  &  &  &  &  &  & 48 & 48 & 0.07\\
\hline
\multicolumn{10}{l}{\rule{0pt}{1em}Only households which were reached by cash, hybrid or voucher modalities are included}\\
\end{tabular}
\end{table}

By far the most common cash delivery mechanism was direct cash payments
-- 85.59\% of households were reached through this mechanism. Transfers
made through Money transfer agents had the highest average transfer
amount.

Next, let us take a look at household package values by activity type:

\begin{table}

\caption{\label{tab:table-usd-values-activity}Average value (USD) of household package values per activity}
\centering
\begin{tabular}[t]{l|r|r|>{}r}
\hline
activity & hhd\_frequencies & total\_value\_usd & avg\_transfer\_value\\
\hline
Provide livestock kits & 900 & 103,950 & \cellcolor[HTML]{440154}{\textcolor{white}{115.50}}\\
\hline
Provide support for income generation & 14,765 & 1,550,694 & \cellcolor[HTML]{481F70}{\textcolor{white}{105.02}}\\
\hline
Provide crops \& vegetables kits & 3,770 & 222,471 & \cellcolor[HTML]{25838E}{\textcolor{white}{59.01}}\\
\hline
Provide monthly cash-based transfers & 404,567 & 21,344,843 & \cellcolor[HTML]{218F8D}{\textcolor{white}{52.76}}\\
\hline
Provide fishery kits & 200 & 8,174 & \cellcolor[HTML]{21A585}{\textcolor{white}{40.87}}\\
\hline
Cash for Work / Food for Assets & 28,520 & 918,812 & \cellcolor[HTML]{32B67A}{\textcolor{white}{32.22}}\\
\hline
Provide monthly food baskets & 74,825 & 1,067,703 & \cellcolor[HTML]{7AD151}{\textcolor{white}{14.27}}\\
\hline
\multicolumn{4}{l}{\rule{0pt}{1em}Only households which were reached by cash, hybrid or voucher modalities are included}\\
\end{tabular}
\end{table}

Overall, the highest average cash transfers were from the provision of
livestock kits and the lowest averages from Cash for work/food for
assets activities (after filtering out food baskets reported as cash).
Please also note that for the table above, all per-household values
above USD 700 have been filtered out as they are likely errors. But
average package values are only part of the picture and significant
variation in transfer values exists within each activity:

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/barplot-facet-usd-hhd-bin-activity-1.pdf}

Clear majorities of the households who received cash-based transfers and
the crop and vegetable kits received valued at USD60-80 and USD 40-60
respectively, indicating that these activities, in addition to fishery
kits and livestock kits, should be relatively easy to standardise.

This section has tried to work around several data entry errors in the
5W reporting -- the per household values of cash transfers have been
recalculated using the number of households reached and the total value
(in USD) of the cash transfers provided. Going forward, it is necessary
to review and confirm these errors with partners and clean the 5W
dataset as many of them have recorded cash transfer values of around USD
10.50 per household as opposed to our recalculated value which averages
out at USD 63; it is suspected that the per beneficiary value may have
been entered as opposed to the value per household.

The partners who have -- likely, in error -- recorded this USD 10.50
transfer are: WFP, Plan International, Save the Children, Myanmar Heart
Development Organisation, People for People, World Vision Myanmar and
People in Need.

The table below compares the different bins for cash-transfer values to
the minimum expenditure basket for food established by the Cash Working
Group -- they have set a floor of MMK 190,555 (or USD 114.55) per
household per month:

\begin{table}

\caption{\label{tab:table-meb-usd-hhd-bin}Monthly cash-based transfer values by percentage of MEB received}
\centering
\begin{tabular}[t]{l|r|r|r|>{}r}
\hline
usd\_hhd\_bin & avg\_pc\_of\_meb & avg\_usd\_month & households & pc\_of\_hhd\\
\hline
<\$10 & 6.11 & 7.00 & 542 & \cellcolor[HTML]{5EC962}{\textcolor{white}{1.26}}\\
\hline
>=\$10\_<\$20 & 9.17 & 10.50 & 3,776 & \cellcolor[HTML]{50C46A}{\textcolor{white}{8.75}}\\
\hline
>=\$20\_<\$40 & 30.55 & 35.00 & 9,853 & \cellcolor[HTML]{21A685}{\textcolor{white}{22.84}}\\
\hline
>=\$40\_<\$60 & 37.63 & 43.10 & 5,786 & \cellcolor[HTML]{21A585}{\textcolor{white}{13.41}}\\
\hline
>=\$60\_<\$80 & 55.01 & 63.01 & 22,135 & \cellcolor[HTML]{440154}{\textcolor{white}{51.31}}\\
\hline
>=\$80\_<\$100 & 80.66 & 92.40 & 115 & \cellcolor[HTML]{7AD151}{\textcolor{white}{0.27}}\\
\hline
>=\$100 & 91.66 & 105.00 & 935 & \cellcolor[HTML]{65CB5E}{\textcolor{white}{2.17}}\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}Only households reached through monthly cash-based transfers are included}\\
\end{tabular}
\end{table}

Overall, 60.17\% of beneficiary households of cash-based transfers have
received 50\% or more of the MEB for the months they were covered. About
10\% of all beneficiary households for monthly cash-based transfers
received under USD 20 per month (less than 10\% of the MEB) and 23\% of
households received between USD 20 and USD 40 (31\% of the MEB) -- this
underscores the importance of standardisation and of the pressing need
to collect more information on whether cash transfers (and food baskets)
have been designed to be full rations, half rations or are instead
intended to be supplementary activities. This is key from a coordination
standpoint as the food security needs of those who have received
supplementary transfers cannot be considered to have been covered.

\hypertarget{partners}{%
\subsection{3. Partners}\label{partners}}

A total of 62 FSC partners classified themselves as implementing
partners within the 5Ws. They are fairly evenly split themselves between
HRP indicators, with 36 contributing towards food and cash assistance
and 39 contributing towards agriculture and other livelihood support. 34
partners have reached less than 10,000 unique beneficiaries and the
median unique beneficiaries reached by partners is 6,118. Below are the
top 10 partners by HRP indicator. As a side note, it remains to be
clarified whether Zigway is a vendor/supplier of WFP or is an
implementing partner -- some follow up with will be necessary; this is
also true for the two private limited companies that also were reported
as implementing partners.

\begin{table}

\caption{\label{tab:table-top-partners-by-hrp-indicator}Top 10 implementing partners by beneficiaries reached, by HRP indicator}
\centering
\begin{tabular}[t]{l|r|l|l|r}
\hline
Partners HRP indicator1 & 1. Number of people who received food and/or cash assistance &   & Partners HRP indicator2 & 2. Number of people who received agriculture and other livelihood support\\
\hline
MRCS & 640,223 &  & CESVI Foundation & 196,869\\
\hline
Open Data Myanmar (ODM) & 400,933 &  & Center for Social Integrity (CSI) & 84,427\\
\hline
Zigway & 223,478 &  & Helen Keller International & 57,287\\
\hline
Hlaingthayar Development Network & 204,275 &  & Action for Green Earth & 29,425\\
\hline
Urban Strength (US) & 201,732 &  & Action Contre la Faim & 23,128\\
\hline
World Vision Myanmar & 180,741 &  & People for People & 18,273\\
\hline
WFP & 110,235 &  & World Vision Myanmar & 18,040\\
\hline
Hlaingthayar Youth Network & 96,145 &  & Myanmar Heart Development Organization & 11,170\\
\hline
Myanmar Heart Development Organization & 70,664 &  & Da-Nu National Affairs organization (DNAO) & 9,266\\
\hline
Karuna Mission Social Solidarity & 70,014 &  & WFP & 8,061\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}Figures reflect beneficiaries reached through direct implementation}\\
\end{tabular}
\end{table}

\hypertarget{distribution-of-partners-by-beneficiaries-and-geographic-reach}{%
\subsubsection{3.1 Distribution of partners by beneficiaries and
geographic
reach}\label{distribution-of-partners-by-beneficiaries-and-geographic-reach}}

Whilst there is quite a bit of variation in the number of beneficiaries
reached, partners' geographic footprints are, on the whole, quite
limited. Only 8 partners have a presence in more than 10 townships, and
only 13 are present in more than 5 townships. 78\% of our partners
(clustered along the bottom of the chart) are present in 5 or less
townships. This distribution of partners is an impediment to a
countrywide response and it is imperative to understand how best to
incentivise partners to expand their footprints.

In terms of activities, 37 partners (60\% of the total) are implementing
only one type of activity. Only one partner (World Vision Myanmar) is
responding across 6 activities. This indicates that it would be
necessary to identify complementary partners for beneficiaries reached
by only one type of activity to achieve comprehensive food security
coverage of the targeted population.

\begin{table}

\caption{\label{tab:table-act-num}Number of implementing partners by number of distinct activities being implemented}
\begin{tabular}[t]{r|r|r|r}
\hline
number\_of\_activities & partners & beneficiaries & pc\_of\_beneficiaries\\
\hline
1 & 37 & 1,446,837 & 44.37\\
\hline
2 & 8 & 922,876 & 28.30\\
\hline
3 & 8 & 193,649 & 5.94\\
\hline
4 & 5 & 306,312 & 9.39\\
\hline
5 & 3 & 192,548 & 5.90\\
\hline
6 & 1 & 198,746 & 6.09\\
\hline
\end{tabular}
\end{table}

\hypertarget{monthly-progress-by-partner}{%
\subsubsection{3.2 Monthly progress by
partner}\label{monthly-progress-by-partner}}

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/partners-progress-over-time-facet-1.pdf}

The plot above shows the top 20 partners by number of beneficiaries
reached in 2021, with the red line indicating June 2021, when the HRP
addendum was approved and published. On the whole, the HRP addendum had
a very large effect on the number of beneficiaries reached -- most
partners enacted a significant ramp up and reached the majority of
beneficiaries after it was published. Exceptions to this include
organisations such as CESVI, Helen Keller International, Save the
Children and Myanmar Heart Development Organisation, who established
most of their caseload prior to July 2021. The next chapter will explore
the effect the HRP addendum had on persons reached by beneficiary type.

\hypertarget{types-of-implementing-partners}{%
\subsubsection{3.3 Types of implementing
partners}\label{types-of-implementing-partners}}

\begin{table}

\caption{\label{tab:table-implementing-partner-type}Average reach by implementing partner type}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
implementing\_partner\_type & avg\_beneficiaries & avg\_townships & avg\_states\\
\hline
INGO & 40,857 & 7.58 & 2.63\\
\hline
NNGO & 60,029 & 3.03 & 1.21\\
\hline
other & 42,642 & 1.00 & 1.00\\
\hline
UN & 118,296 & 32.00 & 8.00\\
\hline
\multicolumn{4}{l}{\rule{0pt}{1em}Figures are averages reached by direct implementation}\\
\end{tabular}
\end{table}

NNGOs, on average, tended to reach more beneficiaries than INGOs, though
INGOs tended to have a much wider geographic reach than NNGOs, perhaps
due to them having more sub-offices as well as the generally tighter
focus of several community-based organisations. There is only one agency
in the ``UN'' category -- WFP; the ``other'' category refers to two
private limited companies which also implemented food security
activities.

\hypertarget{reporting-organisations}{%
\subsubsection{3.4 Reporting
organisations}\label{reporting-organisations}}

There are 72 combinations between reporting organisations and
implementing partners, 23 of which are instances where the reporting
organisation and the implementing partner are the same organisation;
once these are filtered out, all the remaining implementing partners
correspond to just 11 reporting organisations:

\begin{table}

\caption{\label{tab:table-reporting-organisation}Number of implementing partners by reporting organisation}
\begin{tabular}[t]{l|r}
\hline
reporting\_organization & implementing\_partners\\
\hline
WFP & 25\\
\hline
FAO & 6\\
\hline
Finn Church Aid & 4\\
\hline
Save the Children & 4\\
\hline
Cordaid & 2\\
\hline
Mercy Corps & 2\\
\hline
Trocaire & 2\\
\hline
AVSI & 1\\
\hline
Danish Refugee Council & 1\\
\hline
Helvetas & 1\\
\hline
Oxfam & 1\\
\hline
\end{tabular}
\end{table}

This report has used \texttt{implementing\_partners} for most of the
analysis as, by their nature, reporting organisations do not have a
field presence. As a side note, FAO has not classified itself as an
implementing partner, having reported no activities that were directly
implemented by them.

\hypertarget{donors}{%
\subsubsection{3.5 Donors}\label{donors}}

69\% of the rows had the \texttt{donor} column filled. However, this
only represents activities reaching 23\% of all beneficiaries. Below is
a table of the 10 donors (after organisations using their own resources)
whose funding has reached the most beneficiaries and the number of
townships their funding has been used in:

\begin{table}

\caption{\label{tab:donor-table}Top 10 donors by number of beneficiaries reached with their funding}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
donor & beneficiaries & pc\_of\_ben & townships\\
\hline
Organizational own funds & 191,006 & 5.86 & 36\\
\hline
UNDP & 118,113 & 3.62 & 2\\
\hline
humanitarian Assitance and resilience Programme & 87,502 & 2.68 & 7\\
\hline
AICS & 63,986 & 1.96 & 5\\
\hline
MHF & 61,056 & 1.87 & 11\\
\hline
King Philanthropies & 57,287 & 1.76 & 7\\
\hline
ECHO & 26,789 & 0.82 & 3\\
\hline
FCDO & 23,282 & 0.71 & 3\\
\hline
LIFT & 18,958 & 0.58 & 9\\
\hline
European Union (EU) & 13,882 & 0.43 & 4\\
\hline
HELVETAS & 13,851 & 0.42 & 6\\
\hline
\multicolumn{4}{l}{\rule{0pt}{1em}77\% of all beneficiaries (2,513,026 persons) were reported with the `donor` column left blank}\\
\end{tabular}
\end{table}

Additionally, a number of errors have also been observed, including
cases where multiple donors have been combined into one row as well as
numerous instances where UNDP, WFP, FAO and UN WOMEN were classified as
donors as opposed to reporting organisations. Helvetas should also
probably have reported under ``organisations using their own funds''.

\hypertarget{beneficiaries}{%
\subsection{4. Beneficiaries}\label{beneficiaries}}

\hypertarget{beneficiary-disaggregations}{%
\subsubsection{4.1 Beneficiary
disaggregations}\label{beneficiary-disaggregations}}

Currently, in the 5Ws, the vast majority of beneficiary diasaggregations
have been backfilled from census data and do not, consequently, provide
an accurate picture of the population that have been reached by Food
Security interventions. It is not possible to determine how far reality
diverges from what has been reported so far -- meaning that it cannot be
determined if there has been any bias in beneficiary selection and
targeting. It is imperative to begin collecting disaggregated
beneficiary data from partners.

It is estimated that 56.06\% of beneficiaries reported in the 5Ws have
been ``disaggregated'' by backfilling values from the census. This has
been calculated by comparing the proportions of age and sex
disaggregations to the national values set out in the 2021 population
projections -- values within 5\% of the national proportions have been
considered as backfilled from the census.

The plot below shows the differences between the breakdown of
beneficiaries by disaggregation group when only considering values that
have not been backfilled from the census against all values reported in
the 5W dataset. It can be observed that adult females are actually the
largest group of beneficiaries when looking at ``actual'' values;
additionally, the proportions of the beneficiary population who are
elderly are far lower than what has been reflected in the majority of
data reported in the 5Ws.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/barplot-real-disagg-breakdown-1.pdf}

This was confirmed by examining the distributions of beneficiary
disaggregations by implementing partners. From the plot below, we see
that the majority of disaggregated values were very close to the mean
for the entire group. To explain: if partner A reported that 40\% of the
beneficiaries of an activity were adult females, this percentage was
then compared to the mean percentage of beneficiaries formed by adult
females for all the other activities reported by that partner. This
measures whether or not the same proportions were just copied and pasted
throughout the 5W beneficiary disaggregation columns -- it is extremely
unlikely that these percentages would be similar across activities as
implementing partners worked in an average of 50.03 locations. This
level of variability is much lower than what exists in the general
population.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/density-plot-disaggregation-1.pdf}

\hypertarget{types-of-beneficiaries}{%
\subsubsection{4.2 Types of
beneficiaries}\label{types-of-beneficiaries}}

The states and regions in which the FSC is working the most with IDPs
are Chin, Kachin, Sagaing and Shan (North) and Kayah. Overall, 82.68\%
of beneficiaries are from the host/local community, 9.02\% are stateless
persons from Rakhine and 8.24\% are IDPs. Returnees are the rarest type
of beneficiary reached, forming only 0.07\% of all beneficiaries
reached.

\begin{table}

\caption{\label{tab:table-beneficiary-types-state}Percentage breakdown of beneficiary types by state/region}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
state & Host/local Community & Internally Displaced & Returnees & Rakhine stateless & beneficiaries\\
\hline
Ayeyarwady & 100.00 &  &  &  & 99,481\\
\hline
Bago (East) & 66.42 & 33.31 & 0.27 &  & 12,974\\
\hline
Chin & 7.35 & 92.65 &  &  & 17,005\\
\hline
Kachin & 7.68 & 90.65 & 1.67 &  & 89,818\\
\hline
Kayah & 46.88 & 53.12 &  &  & 17,746\\
\hline
Kayin & 67.37 & 32.63 &  &  & 68,108\\
\hline
Magway & 99.03 & 0.97 &  &  & 96,767\\
\hline
Mandalay & 100.00 &  &  &  & 143,526\\
\hline
Mon & 92.50 & 5.88 & 1.62 &  & 48,181\\
\hline
Rakhine & 34.39 & 10.16 &  & 55.45 & 530,202\\
\hline
Sagaing & 25.29 & 74.71 &  &  & 31,985\\
\hline
Shan (East) & 100.00 &  &  &  & 510\\
\hline
Shan (North) & 26.44 & 73.56 &  &  & 73,103\\
\hline
Shan (South) & 100.00 &  &  &  & 15,511\\
\hline
Tanintharyi & 95.64 & 4.13 & 0.22 &  & 4,476\\
\hline
Yangon & 100.00 &  &  &  & 2,011,575\\
\hline
Total & 82.68 & 8.24 & 0.07 & 9.02 & \\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}Each row in the table shows the percentage of each beneficiary type within each state/region}\\
\end{tabular}
\end{table}

Compared to only the 2021 HRP targets (as the IERP does not have
breakdowns of the target by beneficiary type), beenficiary type targets
have been mostly exceeded, neither the targets for returnees/resettled
in Kachin or Shan (North) nor targets for IDPs in Rakhine have been met.
Interestingly, for Rakhine, the targets for the host/local population
have been greatly exceeded and various assumptions can be formulated
regarding this:

\begin{itemize}
\tightlist
\item
  Once targets were met, all further allocations were targeted at the
  local/host community population
\item
  There was better integration of the host population into relief
  programming
\item
  Greater availability of funds and the presence of development donors
\end{itemize}

In Bago (East), Chin, Kayin and particularly Shan (North), the targets
for IDPs have been greatly exceeded, in comparison to the 2021 HRP
targets.

\begin{table}

\caption{\label{tab:table-beneficiary-type-reached-hrp-target}Percentage of 2021 HRP target reached by beneficiary type}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
state & host\_local\% & idp\% & returnees\% & rakhine\_stateless\% & total\%\\
\hline
Bago (East) &  & 171.99 &  &  & 173.38\\
\hline
Chin & 0.00 & 200.74 &  &  & 156.95\\
\hline
Kachin & 88.67 & 110.36 & 32.88 &  & 104.30\\
\hline
Kayin &  & 168.08 &  &  & 196.98\\
\hline
Rakhine & 409.86 & 32.71 &  & 105.75 & 108.83\\
\hline
Shan (North) & 135.56 & 751.31 & 0.00 &  & 400.17\\
\hline
Shan (South) & 0.00 &  &  &  & 0.00\\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}Only HRP/IERP beneficiaries have ben included}\\
\end{tabular}
\end{table}

Stateless persons from Rakhine have the largest average household sizes,
with returnees having the largest variations in household size. With
reference to the plot below, the thick bar in the middle of each box
shows the average household size for each beneficiary type -- this value
is also shown in the text label below the line. The lower and upper
borders of each box indicate the values for the 25th and 75th
percentiles respectively. For instance, households at the 25th
percentile of households in host/local communities have only four
members and households that have around 5 members have more members than
75\% of all the households in that group. Outliers are marked by dots. A
lot of potential data entry errors were observed, especially where less
than one person per household was reported.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/boxplot-household-size-beneficiary-type-1.pdf}

\hypertarget{monthly-progress-by-beneficiary-type}{%
\subsubsection{4.3 Monthly progress by beneficiary
type}\label{monthly-progress-by-beneficiary-type}}

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/beneficiary-types-progress-over-time-facet-1.pdf}

Whilst the numbers of IDPs and Returnees reached did see significant
increases after June 2021, no evidence was observed that this was the
result of the HRP addendum, rather than the continuation of already
existing plans. However, a significant increase in the numbers of
persons in the host/local community reached after June 2021 has been
noted -- almost all host/local community beneficiaries were reached
after the publication of the HRP addendum. Conversely, the progress
amongst stateless persons in Rakhine slowed substantially after the
publication of the addendum.

\begin{table}

\caption{\label{tab:table-ben-type-before-after-ierp}Reached by beneficiary type, before and after HRP addendum}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
beneficiary\_type & before\_addendum & after\_addendum & Total & \%before & \%after\\
\hline
Host/local Community & 198,856 & 2,028,907 & 2,227,763 & 8.93 & 91.07\\
\hline
Rakhine stateless & 246,891 & 47,101 & 293,992 & 83.98 & 16.02\\
\hline
Internally Displaced & 138,009 & 123,436 & 261,445 & 52.79 & 47.21\\
\hline
Returnees & 1,046 & 1,278 & 2,324 & 45.01 & 54.99\\
\hline
\multicolumn{6}{l}{\rule{0pt}{1em}Only HRP/IERP beneficiaries are included}\\
\end{tabular}
\end{table}

\hypertarget{gaps-in-monthly-programming}{%
\subsubsection{4.4 Gaps in monthly
programming}\label{gaps-in-monthly-programming}}

\begin{table}

\caption{\label{tab:table-gaps-months}Number of beneficiaries and locations by duration of gaps in implementation}
\centering
\begin{tabular}[t]{r|r|r|r|r}
\hline
gap\_months & locations & townships & beneficiaries & pc\_of\_ben\\
\hline
0 & 282 & 35 & 457,448 & 51.48\\
\hline
1 & 49 & 21 & 72,929 & 8.21\\
\hline
2 & 123 & 22 & 64,222 & 7.23\\
\hline
3 & 406 & 12 & 236,978 & 26.67\\
\hline
4 & 8 & 5 & 8,485 & 0.95\\
\hline
5 & 9 & 5 & 28,195 & 3.17\\
\hline
8 & 1 & 1 & 20,393 & 2.29\\
\hline
\multicolumn{5}{l}{\rule{0pt}{1em}Only beneficiaries of monthly activities that recurred at least once are included}\\
\end{tabular}
\end{table}

49\% of beneficiaries of monthly activities experienced gaps or delays
in monthly programming, with the most common delay being 3 months. The
8-month delay was the provision of monthly food baskets in Buthidaung,
where distributions only occurred in February and November 2021. The
5-month delays were all from locations in Rakhine and Kachin. Overall,
gaps in monthly programming were experienced in 39 townships, with the
majority orginating from Kachin, Ayeyarwady and Rakhine.

There are 274 entries coded as being implemented on a monthly basis that
have not recurred -- that is, they have only been implemented once: the
FSC needs to check with partners if these are merely the first instances
of these activities, or if there have been issues with access, security
or funding or if they are errors in data entry .

\hypertarget{potential-for-post-distribution-monitoring}{%
\subsubsection{4.5 Potential for post-distribution
monitoring}\label{potential-for-post-distribution-monitoring}}

The table below shows activities which have been implemented for 6
months or more, the number of locations they were implemented in and the
number of unique beneficiaries reached by activities meeting these
criteria. The possibility of joint monitoring -- or at least the joint
review and analysis of monitoring data -- shopuld be explored, in
consultation with these partners. The rationale being that 6 months of
implementation should be a long enough period of time to make impact
monitoring feasible. Additionally, joint monitoring will be further
facilitated by the similarity of these activities, almost all of which
are recurrent cash transfers or distributions of food baskets.

\begin{table}

\caption{\label{tab:table-monthly-activities-6-9-months}Number of beneficiaries, by activity, who have received at least 6 months of recurrent food security support}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
activity & partners & locations & beneficiaries\\
\hline
Provide monthly cash-based transfers & 7 & 233 & 195,942\\
\hline
Provide monthly food baskets & 7 & 44 & 147,819\\
\hline
Provide technical training & 2 & 413 & 57,887\\
\hline
Provide crops \& vegetables kits & 1 & 406 & 57,287\\
\hline
Provide support for income generation & 1 & 407 & 57,287\\
\hline
Cash for Work / Food for Assets & 1 & 1 & 245\\
\hline
\multicolumn{4}{l}{\rule{0pt}{1em}Only includes beneficiaries (not unique but maximum by location by activity) who have received more than 6 months of support}\\
\end{tabular}
\end{table}

These are the partners who have implemented monthly food baskets and
monthly cash-based transfers for more than 6 months:

\begin{table}

\caption{\label{tab:table-partners-6-months}Partners who have implemented cash transfers and food baskets for at least 6 months}
\centering
\begin{tabular}[t]{l|r|r}
\hline
implementing\_partners & Provide monthly cash-based transfers & Provide monthly food baskets\\
\hline
Karuna Mission Social Solidarity & 53,244 & 85\\
\hline
Myanmar Heart Development Organization & 30,185 & 57,638\\
\hline
People for People & 23,982 & \\
\hline
Plan International & 37,657 & \\
\hline
Save the Children & 144 & \\
\hline
WFP & 39,192 & 42,002\\
\hline
World Vision Myanmar & 11,538 & 19,559\\
\hline
Action for Green Earth &  & 18,755\\
\hline
People Hope Community Development (PHCD) &  & 8,872\\
\hline
Together for Sustainable Development &  & 908\\
\hline
\multicolumn{3}{l}{\rule{0pt}{1em}Only includes beneficiaries (not unique but maximum by location by activity) who have received more than 6 months of support}\\
\end{tabular}
\end{table}

\hypertarget{next-steps-for-2022}{%
\subsection{5. Next steps for 2022}\label{next-steps-for-2022}}

\hypertarget{positioning-for-2022}{%
\subsubsection{5.1 Positioning for 2022}\label{positioning-for-2022}}

The PIN for 2022 is much more evenly spread across the country than it
was in 2021: with reference to the plot below, Magway and Mandalay have
some of the lowest proportions of vulnerable persons in relation to the
total state population, meaning that careful beneficiary selection and
tight vulnerability in these areas will necessary to avoid excessive
inclusion errors.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/barplot-pin-vul-state-1.pdf}

The average percentage of a state's PIN that is included in the target
is 22.18\%, though there are some very notable exceptions at both the
superior and inferior ends of the scale:

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/stacked-barplot-pin-target-1.pdf}

Food Security Cluster partners are not well-positioned to cover the 2022
population in need and targets. Partners are largely concentrated in
Kachin, Rakhine and Yangon, with only one partner present in Shan (East)
and two in Tanintharyi.

Overall, 57\% of townships, containing 48\% of the 2022 target, do not
have any partners present. This lack of nationwide coverage will be one
of the most important constraints that the FSC will face in meeting the
2022 needs of vulnerable, food insecure persons and IDPs -- and
resolving this will necessitate both increasing partner coverage and
finding new partners for the cluster.

\includegraphics{2021_fsc_5w_initial_observations_files/figure-latex/map-partners-target-township-1.pdf}

This mismatch between partner existing partner footprints and the PIN
for 2022 highlights the need for more dedicated field-level
coordination. This will be necessary in order to reach out to and
cultivate new partners and encourage existing partners to expand their
operations. Strengthened inter-cluster will also be key to ensure that
the needs of persons in need are being met in a comprehensive manner.

\hypertarget{next-steps}{%
\subsubsection{5.2 Next steps}\label{next-steps}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Communicate to partners that Yangon is severely oversubscribed in
  comparison to the rest of the country, above all in the townships of
  Hlaingtharya, Shwepyithar, Dagon Myothit (Seikkan), Dala and North
  Okkalapa.
\item
  Collect existing intervention packages from partners in order to begin
  the process of standardisation and to support the review of food
  baskets for their caloric and nutritional value. Perform additional
  analysis to understand if beneficiaries in close proximity to each
  other have received widely divergent package values. Additionally,
  speak with partners to understand why cash transfer values vary even
  within the same activity implemented by the same partner.
\item
  Revisit areas which have only received smaller supplementary transfers
  -- transfers covering a low percentage of the MEB cannot be considered
  to have met the food security needs for that area -- other partners
  may be necessary to cover the gap.
\item
  Advocate for the expansion of partners' geographic footprints to reach
  the remaining 179 townships which have yet to benefit from any FSC
  activities. The effects of the current crisis in Myanmar have not been
  determined by an epicentre or a stormpath and there is no programmatic
  rationale for the response to be so uneven. This advocacy should be
  targeted at the ICCG, Cluster partners and at donors.
\item
  Collect 5W data from other clusters so that multi-sector coverage may
  be reviewed. Clean and process conflict data so that it may be
  cross-referenced with partners' coverage. Share raw data with other
  Clusters to improve coordination.
\item
  Work with partners to determine their current capacities to submit age
  and sex-disaggregated beneficiary data. Develop a workplan to ensure
  that they can meet reporting requirements.
\item
  Solicit monitoring reports from partners and explore the possibility
  of joint monitoring.
\item
  Revise the 5W template -- in consultation with partners -- in order to
  address the data collection issues identified.
\end{enumerate}

\hypertarget{reference-table-townships}{%
\subsection{6. Reference table --
townships}\label{reference-table-townships}}

The reference table below may be sorted and filtered by any of the
columns.

\hypertarget{interactive-reference-maps}{%
\subsection{7. Interactive reference
maps}\label{interactive-reference-maps}}

Click
\textbf{\href{https://food-security-cluster-myanmar.github.io/mmr_5w_initial_observations_maps/}{here}}
to load maps

\hypertarget{bookmark}{%
\subsubsection{bookmark}\label{bookmark}}

\end{document}
