---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=9, message = FALSE, warning=FALSE)
library(tidyverse)
library(readxl)
library(lubridate)
library(stringi)
library(pander)
library(janitor)
library(fuzzyjoin)
library(scales)
library(magrittr)
library(sf)
library(s2)
library(bookdown)
library(data.table)
library(ggsflabel)
library(patchwork)
library(plotly)
library(kableExtra)
library(DT)
library(viridis)

theme_set(theme_light())

# disabling scientific notation
options(scipen = 100)

# pander tables all in one row
panderOptions('table.split.table', Inf)

# pander thousands separator
panderOptions("big.mark", ",")

# replace 
opts <- options(knitr.kable.NA = "")

`%out%` <- Negate(`%in%`)

# reading in 5ws
fsc <- read_csv("fsc5w_2021.csv") %>%  
  rename(admin5_pcode = admin4_pcode)

```

```{r}
fsc %>%  
  count(activity, activity_description, sort = TRUE)
```


```{r}
new_act <- read_excel("FSC Objectives and Activities 2022 HRP_aung.xlsx") %>% 
  clean_names() %>% 
  select(-c(column1, column2))%>% 
  mutate(sub_activities = str_remove_all(sub_activities, "\r\n"),
         sub_activities = str_remove_all(sub_activities, "\t"))

glimpse(new_act)

new_act %>% count(fsc_main_activity, sub_activities)

new_act 
```

```{r facet-usd-package-by-activity}
fsc %>% 
  # filter(unique_beneficiaries == "Yes" & !is.na(usd_hhd_bin)) %>%
  filter(delivery_modality %in% c("Cash", "Hybrid (In-kind & Cash)", "Voucher")) %>%
  filter(activity %out% c("Provide fishery kits", "Provide livestock kits")) %>% 
  filter(new_value_hhd < 700 & activity != "Provide monthly food baskets") %>% 
  group_by(activity, implementing_partners) %>% 
  summarise(mean_usd = mean(new_value_hhd), 
            beneficiaries = sum(beneficiaries), 
            households = sum(households)) %>% 
  arrange(desc(beneficiaries)) %>% 
  mutate(mean_usd = ifelse(activity == "Provide monthly cash-based transfers", mean_usd / (beneficiaries / households), mean_usd	)) %>% 
  top_n(5) %>% 
  ggplot(aes(x = mean_usd, y = implementing_partners, fill = activity)) +
  scale_x_continuous(labels = comma_format(accuracy = 1)) +
  geom_col() + 
  facet_wrap(~ activity, scales = "free", ncol = 2) +
  theme(legend.position = "none") +
  labs(x = "Average USD value of package", 
       y = "Implementing partner", 
       title = "Top 5 partners (by beneficiaries) and the average USD value of their packages by activity type", 
       subtitle = "Only includes activities reported under cash, hybrid and voucher modalities; all values are per month per household, except cash transfers which are per person")


```

```{r}
fsc %>% 
  group_by(township) %>% 
  summarise(locations = n_distinct(location)) %>% 
  arrange(desc(locations))

fsc %>% filter(township == "Sittwe") %>% 
 # group_by(location_type) %>% 
  select(location, location_type) %>% distinct() %>% arrange(location)
  summarise(locations = n_distinct(location))
  
fsc %>% filter(str_detect(activity, "fishery")) %>% 
  group_by(date) %>% 
  summarise(beneficiaries = sum(beneficiaries))
```

```{r}
low_value_location <- fsc %>% 
  filter(unique_beneficiaries == "Yes") %>% 
  filter(usd_hhd_bin %in% c("<$10", ">=$10_<$20", ">=$20_<$40") & new_value_hhd > 0) %>% 
  filter(!is.na(location)) %>% 
  group_by(township, location, activity) %>% 
  summarise(ben_freq = sum(beneficiaries), 
            households = sum(households), 
            mean_usd = mean(new_value_hhd), .groups = "drop") %>% 
  pivot_wider(names_from = activity, values_from = mean_usd) %>%
  mutate(total_freq = rowMeans(cbind(`Provide monthly cash-based transfers`,
                                    `Cash for Work / Food for Assets`,
                                    `Provide monthly food baskets`,
                                    `Provide support for income generation`,
                                    `Provide technical training`,
                                    `Provide crops & vegetables kits`), na.rm = TRUE)) %>% 
  mutate(act_count = rowSums(!is.na(cbind(`Provide monthly cash-based transfers`,
                                    `Cash for Work / Food for Assets`,
                                    `Provide monthly food baskets`,
                                    `Provide support for income generation`,
                                    `Provide technical training`,
                                    `Provide crops & vegetables kits`)))) 

fsc %>% 
  inner_join(low_value_location %>% 
               select(township, location), by = c("township", "location")) %>% 
  group_by(township, location) %>% 
  summarise(ben_freq = sum(beneficiaries), 
            households = sum(households),
            activities = n_distinct(activity),
            mean_usd = mean(new_value_hhd, na.rm = TRUE), .groups = "drop") %>% 
  count(activities) %>% adorn_percentages("col")

  
```

```{r}
fsc %>%  
  group_by(implementing_partners, activity, activity_description) %>% 
  slice(which.max(beneficiaries)) %>% 
  select(implementing_partners, activity, activity_description) %>% 
  write_csv("activity_description.csv")
```


### new activities 

```{r}
fsc_act_new <- fsc %>% 
  mutate(activity_new = case_when(str_detect(activity_description, "Local Chicken support") ~
                                    "provision of livestock kits",
                                  activity == "Cash for Work / Food for Assets" ~ 
                                    "food/cash for work/assets",
                                  str_detect(activity_description, "home|Home") & 
                                    !str_detect(activity_description, "training|Training|Training,") ~
                                    "provision of kitchen garden kits",
                                  activity == "Provide crops & vegetables kits" & 
                                    str_detect(activity_description, "pumps|till|drum|Tiller|Drum") ~ 
                                    "provision of community infrastructure and equipment",
                                  activity == "Provide crops & vegetables kits" ~ 
                                    "provision of crop, vegetable and seed kits",
                                  activity == "Provide fishery kits" ~ 
                                    "provision of fishery kits",
                                  activity == "Provide livestock kits" ~ 
                                    "provision of livestock kits",
                                  activity %in% c("Provide monthly cash-based transfers", "Provide monthly food baskets") & 
                                    str_detect(activity_description, "Lifesaving|lifesaving|acute|Acute") ~ 
                                    "food distributions (in kind/voucher/cash), severe",
                                  # what to do about MVC, malnourished children and PLW?
                                  activity %in% c("Provide monthly cash-based transfers", "Provide monthly food baskets")  ~
                                    "food distributions (in kind/voucher/cash), moderate",  
                                  activity == "Provide support for income generation" & 
                                    !str_detect(activity_description, "agriculture input|farming") ~
                                    "income-generating activities and small grants",
                                  activity  == "Provide support for income generation"  ~
                                    "income-generating activities and small grants",
                                  activity == "Provide technical training" & 
                                    str_detect(activity_description, "farm|Farm|FFS|pesticide|ferti|agri|Agri|gardening|Seed|seed|SSA") ~ 
                                    "FFS and farmer training", 
                                  activity == "Provide technical training" ~
                                    "vocational training", 
                                  activity_description %in% c("Provide Voucher Cards to buy agriculture inputs for their agricultural works",
                                                              "Cash for farming (Livestock and Agri)") ~ 
                                    "provision of crop, vegetable and seed kits",
                                  TRUE ~ NA_character_)) 

# new activities not yet included:
# microfinance activities
# distribution of HEB and fortified rice for acute emergencies

# T/F nutrition messaging included?

fsc_act_new %>% 
  group_by(activity_new) %>% 
  summarise(count = n(),
            beneficiaries = sum(beneficiaries)) %>% 
  mutate(pc = beneficiaries / sum(beneficiaries))

fsc_act_new %>% 
  group_by(activity_new, activity) %>% 
  summarise(beneficiaries = sum(beneficiaries))

fsc_act_new %>% 
  filter(activity_new %in%
           c("food distributions (in kind/voucher/cash), severe", "food distributions (in kind/voucher/cash), moderate")) %>%
  group_by(activity_new) %>% 
  summarise(beneficiaries = sum(beneficiaries)) %>% 
  mutate(pc = beneficiaries / sum(beneficiaries))

fsc_act_new %>% 
  filter(activity_new == "provision of kitchen garden kits") %>% 
  distinct(activity_description) %>% pull()

fsc_act_new %>% 
  filter(activity_new == "income-generating activities and small grants") %>% 
  distinct(activity_description) %>% pull()

# recode as home garden kitchen garden kit
fsc_act_new %>% filter(activity_description == "Sewing Machine support for children/youth who completed vocational training") %>% select(implementing_partners, activity)

# not food security -- goes to UNDP? SERRP? 
# "Sewing Machine support for children/youth who completed vocational training" 
# "Start-up kits distribution for Tailoring Vocational Training"

fsc_act_new %>% 
  filter(activity_new == "vocational training" & !is.na(activity_description)) %>% 
  distinct(activity_description) %>% pull()

fsc_act_new %>% 
  distinct(activity_new) %>% arrange(activity_new)

```

```{r}
  # count(activity_new)
  filter(activity_new %in% c("food distributions (in kind/voucher/cash), lifesaving/crisis", 
                             "food distributions (in kind/voucher/cash), moderate/severe")) %>%
  group_by(activity_new) %>% 
  summarise(count = n(),
            beneficiaries = sum(beneficiaries)) %>% 
  mutate(pc = beneficiaries / sum(beneficiaries))
  # filter(is.na(activity_new)) %>% 
  distinct(activity_description) %>% pull()

fsc %>%  filter(activity_description == "In target IDP camps/locations, the basic food will be provided through provision of cash grants depending on access functioning of markets. In case of cash grants 12.500 MMK/month/person which is in line with the basked as advised by the cash working group in Yangon. The cash will be provided per person the direct distribution will be done involving the camp management but the partner remains responsible. Cash will be distributed in two tranches.")



fsc %>% filter(str_detect(activity_description, "chicken|Chicken")) %>% 
  distinct(activity_description) %>% pull()

fsc %>% count(beneficiary_type)
```


```{r}
glimpse(locations)

locations %>% 
  rename(village_code = payam_code) %>% 
  mutate(location_type = recode(location_type, "payam" = "village"),
         location = str_to_title(location)) %>% 
  left_join(read_excel("Myanmar PCodes Release_9.3_Jan2021_Countrywide(Villages_only).xlsx") %>% 
              select(admin4_pcode = VT_Pcode, vt_name = Village_Tract_Name_Eng, village_code = Village_Pcode) %>% 
              mutate(village_code = as.character(village_code)), by = "village_code") %>% 
  select(state_name, admin1_pcode, township_name, admin3_pcode, vt_name, admin4_pcode, location_name = location, 
         location_pcode = location_code, village_code, camp_pcode) %>% 
  glimpse()
  write_csv("locations.csv")

```

