---
title: "Shelter/NFI/CCCM Camps and Myanmar Food Security Cluster 5Ws"
author: "Sean Ng"
date: "04/02/2022"
output: 
  html_document:
    code_download: true
    theme: readable
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: false
    collapsed: false
always_allow_html: true   
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=9, message = FALSE, warning=FALSE)
library(tidyverse)
library(readxl)
library(lubridate)
library(stringi)
library(pander)
library(janitor)
library(fuzzyjoin)
library(scales)
library(magrittr)
library(sf)
library(s2)
library(bookdown)
library(data.table)
library(ggsflabel)
library(patchwork)
library(plotly)
library(kableExtra)
library(DT)
library(viridis)

theme_set(theme_light())

# disabling scientific notation
options(scipen = 100)

# pander tables all in one row
panderOptions('table.split.table', Inf)

# pander thousands separator
panderOptions("big.mark", ",")

# replace 
opts <- options(knitr.kable.NA = "")

`%out%` <- Negate(`%in%`)

# function for transposing df
transpose_df <- function(df) {
  t_df <- data.table::transpose(df)
  colnames(t_df) <- rownames(df)
  rownames(t_df) <- colnames(df)
  t_df <- t_df %>%
    tibble::rownames_to_column(.data = .) %>%
    tibble::as_tibble(.)
  return(t_df)
}

# function beneficiary summaries
sum_ben <- function(df, column_var){
  
  column_var <- enquo(column_var)
  
  df %>%
    group_by(!!column_var) %>% # must add bang-bang
    summarise(beneficiaries = sum(beneficiaries)) %>% 
    arrange(desc(beneficiaries))
    
}

# function beneficiary summaries, 2 grouped variables
sum_ben2 <- function(df, column_var1, column_var2){
  
  column_var1 <- enquo(column_var1)
  column_var2 <- enquo(column_var2)
  
  df %>%
    group_by(!!column_var1, !!column_var2) %>% # must add bang-bang
    summarise(beneficiaries = sum(beneficiaries)) %>% 
    arrange(desc(beneficiaries))
    
}

revlog_trans <- function(base = exp(1)){
    ## Define the desired transformation.
    trans <- function(x){
                 -log(x, base)
                }
    ## Define the reverse of the desired transformation
    inv <- function(x){
                 base^(-x)
                }
    ## Creates the transformation
    trans_new(paste("revlog-", base, sep = ""),
              trans, ## The transformation function (can be defined using anonymous functions)
              inv,  ## The reverse of the transformation
              log_breaks(base = base), ## default way to define the scale breaks
              domain = c(1e-100, Inf) ## The domain over which the transformation is valued
             )
    }


# partial_join function
partial_join <- function(x, y, by_x, pattern_y){
  
 idx_x <- sapply(y[[pattern_y]], grep, x[[by_x]])
 idx_y <- sapply(seq_along(idx_x), function(i) rep(i, length(idx_x[[i]])))

 df <- dplyr::bind_cols(x[unlist(idx_x), , drop = F],
                        y[unlist(idx_y), , drop = F])
 return(df)
 
}

# reading in townships from geoadmins 
townships <- read_excel("FSC 5W 2021 - GEOADMINS_final 19.xlsx",
           sheet = "GEOADMINS") %>% 
  clean_names() %>% 
  select(admin1pcode_4:admin3pcode) %>% 
  rename(admin1_pcode = admin1pcode_4,
         admin3_pcode = admin3pcode,
         state_name   = state_5,
         township_name  = county) %>% 
  remove_empty()

# locations dataset 
locations <- bind_rows(
  
  read_excel("FSC 5W 2021 - GEOADMINS_final 19.xlsx", # payams 
             sheet = "GEOADMINS") %>% 
    clean_names() %>% 
    select(state_name:payam_code) %>% 
    rename(admin1_pcode = state_code_12,
           township_name = county_name, 
           admin3_pcode = county_code,
           location = payam_name) %>%
    remove_empty() %>% 
    mutate(location_type = paste0("payam")),
  
  read_excel("FSC 5W 2021 - GEOADMINS_final 19.xlsx", # camps
             sheet = "GEOADMINS") %>% 
    clean_names() %>% 
    select(county_name1:p_code_camp) %>% 
    rename(township_name = county_name1,
           admin3_pcode = state_code_23,
           location = camps, 
           camp_pcode = p_code_camp) %>% 
    remove_empty() %>% 
    mutate(location_type = paste0("camp")) %>% 
    left_join(townships %>% select(state_name, admin1_pcode, admin3_pcode), 
              by = c("admin3_pcode")) %>% 
    relocate(admin1_pcode) %>% 
    relocate(state_name),
  
  read_excel("FSC 5W 2021 - GEOADMINS_final 19.xlsx", # industrial zones
             sheet = "GEOADMINS") %>% 
    clean_names() %>%
    select(state_28:industrial_zones) %>% 
    rename(state_name = state_28, 
           admin1_pcode = admin1pcode_29,
           location = industrial_zones) %>%
    remove_empty() %>% 
    regex_left_join(townships %>% select(township_name, admin3_pcode),
                    by = c("location" = "township_name")) %>% 
    # replacing the NAs with 0s so the filter doesn't drop them 
    replace_na(list(township_name = 0, admin3_pcode = 0, admin1_pcode = 0)) %>%
    filter(admin3_pcode != "MMR013040") %>% # removing all the matches between Hlaingtharya and Hlaing
    filter(admin3_pcode != "MMR011006") %>% # removing all the matches between Yenangyaung and Ye
    mutate(location_type = paste0("industrial_zone"))
  
)%>%
  mutate(location_code = case_when(location_type == "camp" ~ camp_pcode,
                                   location_type == "payam" ~ payam_code,
                                   location_type == "industrial_zone" ~ NA_character_)) %>%
  mutate(locations_fuzzy = str_replace_all(location, "[[:punct:]]", ""),
         locations_fuzzy = tolower(locations_fuzzy),
         location = tolower(location))


# this exists for the HRP / non-HRP column 
hrp2021_adm3_list <- pin %>% filter(hrp_version == "hrp") %>% pull(admin3_pcode)

# reading in 5ws
fsc <- read_excel(
  "FSC 5W 2021 - GEOADMINS_final 19_Jan to Dec 2021 IM Combined_Draft_28012022.xlsx",
                  sheet = "FSC 5W Activites",
                  skip = 5) %>% 
  janitor::clean_names() %>% 
  select(month_of_implementation:hrp_version) %>% 
  rename_all(~str_replace_all(., "^number_of_", "")) %>%
  rename_all(~str_replace_all(., "^number_", "")) %>% 
  rename(admin5_pcode = admin3_pcode, 
         admin3_pcode = admin2_pcode,
         beneficiaries = reached_beneficiaries,
         households = reached_households,
         beneficiary_type = beneficiaries_type) %>% 
  mutate(industrial_zones = replace(industrial_zones, industrial_zones == "No", NA),
         frequency = replace(frequency, frequency == "N/A", NA)) %>% 
  mutate(location = case_when(camp != "NA" ~ camp,
                              industrial_zones != "NA" ~ industrial_zones,
                              village_ward_town != "NA" ~ village_ward_town)) %>% 
  mutate(location_type = case_when(camp != "NA" ~ "camp",
                              industrial_zones != "NA" ~ "industrial_zone",
                              village_ward_town != "NA" ~ "village_ward_town"),
         locations_fuzzy = str_replace_all(location, "[[:punct:]]", " "),
         locations_fuzzy = tolower(locations_fuzzy),
         location = tolower(location)) %>%
  mutate(total_value_mmk = value_per_household * households,
         date            = my(month_of_implementation),
         u_ben           = ifelse(unique_beneficiaries == "Yes", beneficiaries, 0)) %>% 
  mutate(state = as.character(fct_recode(state, 
                            "Kachin" = "kachin")),
         frequency = recode(frequency, "monthly" = "Monthly"),
         township = recode(township, "kyaukme" = "Kyaukme")) %>% 
  mutate(new_value_hhd = total_value_usd / households,
         new_value_person = total_value_usd / beneficiaries,
         usd_hhd_bin = 
           case_when(new_value_hhd < 10 ~ "<$10",
                     new_value_hhd >= 10 & new_value_hhd < 20 ~ ">=$10_<$20",
                     new_value_hhd >= 20 & new_value_hhd < 40 ~ ">=$20_<$40",
                     new_value_hhd >= 40 & new_value_hhd < 60 ~ ">=$40_<$60",
                     new_value_hhd >= 60 & new_value_hhd < 80 ~ ">=$60_<$80",
                     new_value_hhd >= 80 & new_value_hhd < 100 ~ ">=$80_<$100",
                     new_value_hhd >= 100 ~ ">=$100",
                     TRUE ~ NA_character_),
         usd_hhd_bin = fct_relevel(usd_hhd_bin, c("<$10", ">=$10_<$20", ">=$20_<$40", ">=$40_<$60", 
                                                  ">=$60_<$80", ">=$80_<$100", ">=$100"))) %>% 
  mutate(hrp_indicator =
          recode(hrp_indicator,
          "Number of people who received food and/or cash assistance" = 
            "1.Number of people who received food and/or cash assistance",
          "Number of people who received agriculture and other livelihood support, contributing to household food security" =
            "2.Number of people who received agriculture and other livelihood support")) %>% 
  mutate(beneficiary_type = str_trim(beneficiary_type)) %>% 
  mutate(beneficiary_type = as.character(fct_recode(beneficiary_type, 
               "Rakhine stateless" = "Non-displaced stateless people in Rakhine"))) %>% 
  mutate(activity = recode(activity, 
                          "Provide monthly food baskets through in-kind assistance to acutely food insecure population in rural areas" = 
                            "Provide monthly food baskets",
                          "Provide technical training (agriculture, livestock breeding, livelihood)" = "Provide technical training",
                          "Provide support for Income Generating Activities" = "Provide support for income generation",
                          "Provide monthly cash-based transfers to acutely food insecure population in rural areas" =
                            "Provide monthly cash-based transfers",
                          "Cash for Work / Food for Assets activities" = "Cash for Work / Food for Assets",
                          "Provide fishery kits (in-kind / CBT)" = "Provide fishery kits",
                          "Provide crops & vegetables kits (in-kind / CBT)" = "Provide crops & vegetables kits",
                          "Provide livestock kits (in-kind / CBT)" = "Provide livestock kits")) %>% 
  mutate(implementing_partners = recode(implementing_partners, 
                                        "Save the children" = "Save the Children")) %>% 
  mutate(implementing_partner_type = 
           ifelse(implementing_partners %in% c("Kaw Lah Foundation", "Hakha Baptist Association (HBA)", "Arkan Research and Watch",
                                               "Hlaing Development Network", "Mangrove Service Network (MSN)", "Kyal Sin May",
                                               "Swan Saung Shin", "Sein Lei Ayeyar"), "NNGO", implementing_partner_type),
         implementing_partner_type = 
           ifelse(implementing_partners %in% c("Single Touch Point Company Limited (STP)", "Neo Prospect Company Limited"), 
                  "other", implementing_partner_type),
         implementing_partner_type = ifelse(implementing_partners == "Helen Keller International", "INGO", implementing_partner_type)) %>%  
  mutate(hrp_ierp = case_when(admin3_pcode %in% hrp2021_adm3_list ~ "hrp",
                             date > "2021-05-01" ~ "ierp",
                             TRUE ~ "non_hrp")) %>% 
  mutate(covid_19_response = recode(covid_19_response, 
                                          "No" = "no", "Yes" = "yes"),
               covid_19_response = replace_na(covid_19_response, "no"))

```

### read camp_point df

```{r}
camp_points <- read_excel("Shelter NFICCCM Cluster_ Coordinates.xltx") %>% 
  clean_names() %>%
  mutate(state = recode(state, "cRS" = "Rakhine")) %>% 
  rename(township = township_name) %>% 
  select(-state) %>% 
  left_join(townships, by = "township") %>%  
  mutate(camp_name_low = tolower(camp_name))

camp_points %>%  filter(township == "Myitkyina")
```

### fuzzy joining camps lists

```{r}

# fsc camps df
fsc_camps <- fsc %>%  
  mutate(admin5_pcode = as.character(admin5_pcode)) %>%
  filter(unique_beneficiaries == "Yes" & location_type == "camp") %>% 
  group_by(location, admin5_pcode, admin3_pcode, state, township) %>%  
  summarise(beneficiaries = sum(beneficiaries),
            partners = n_distinct(implementing_partners),
            activities = n_distinct(activity), .groups = "drop")

# regex_left_join
fsc_camps %>%  
  regex_left_join(camp_points %>% 
              select(camp_name_low, p_code), by = c("location" = "camp_name_low"))  %>% 
  relocate(p_code, .after = admin5_pcode) %>%  
  relocate(camp_name_low, .after = location) %>% 
  filter(!is.na(camp_name_low)) %>% arrange(admin3_pcode)

# partial_join function
fsc_camps %>%
  partial_join(x = ., y =camp_points %>% 
                 select(camp_name_low, camp_name, p_code), by_x = "location", pattern_y = "camp_name_low") %>% 
  relocate(p_code, .after = admin5_pcode) %>%  
  relocate(camp_name, .after = location) %>% 
  arrange(admin3_pcode)

# of all the options, stringdist_left_join performs the best
camps_joined <- fsc_camps %>%
  stringdist_left_join(camp_points %>% 
              select(camp_name_low, camp_name, p_code, admin3_pcode), 
              by = c("location" = "camp_name_low", "admin3_pcode"), ignore_case = TRUE, distance_col = "distance") %>% 
  select(-distance) %>% 
  relocate(p_code, .after = admin5_pcode) %>%  
  relocate(camp_name_low, .after = location) %>% 
  group_by(location) %>% 
  slice(which.min(location.distance))


```


### histogram of FSC-assisted camps not in Shelter/NFI/CCCM list

```{r}
fsc_camps %>% 
  anti_join(camps_joined %>%  
              select(location), by = "location") %>% 
  ggplot(aes(x = beneficiaries, fill = state)) + 
  geom_histogram() + 
  scale_x_continuous(trans = "log10", labels = comma_format(accuracy = 1)) +
  labs(x = "Number of FSC beneficiaries", 
       y = "Number of camps", 
       title = "Histogram of FSC-assisted camps not in Shelter/NFI/CCCM list")
  
```




```{r}
camp_points %>% filter(state == "Rakhine") %>% arrange(desc(population))

# camps not in mimu dataset
camp_points %>% 
  anti_join(locations %>%
              filter(!is.na(camp_pcode)) %>% 
              select(camp_pcode),
            by = c("p_code" = "camp_pcode")) 

camp_points %>%  
  

glimpse(camp_points)

glimpse(townships)


```

```{r}
locations %>% filter(!is.na(camp_pcode) & township == "Injangyang")
```

```{r}

```


```{r}
unmatched <- fsc %>% 
    mutate(location_type = recode(location_type, 
                                  "village_ward_town" = "payam")) %>%
  filter(!is.na(location)) %>% 
  select(admin3_pcode, locations_fuzzy, location, location_type) %>%   
  left_join(locations %>%  select(location, location_code), by = "location") %>%  
  filter(is.na(location_code))

unmatched$ID <- seq.int(nrow(unmatched))

match1 <- unmatched %>% 
  select(-location_code) %>% 
  stringdist_left_join(locations %>%   
                         select(locations_fuzzy, location_code, admin3_pcode),
            by = c("locations_fuzzy", "admin3_pcode"), ignore_case = TRUE, distance_col = "distance") 

unmatched %>%
  mutate(locations_fuzzy = tolower(locations_fuzzy)) %>%
  left_join(
    match1 %>% 
      filter(admin3_pcode.distance == 0) %>% 
      group_by(locations_fuzzy.x) %>% 
      slice(which.min(locations_fuzzy.distance)) %>% 
      select(admin3_pcode = admin3_pcode.y, locations_fuzzy.y, locations_fuzzy.x),
  by = c("admin3_pcode" = "admin3_pcode", "locations_fuzzy" = "locations_fuzzy.x")) %>% 
  filter(!is.na(locations_fuzzy.y))


match2 <- unmatched %>%  
  select(-location_code) %>%
  regex_left_join(locations %>%
                       select(locations_fuzzy, admin3_pcode, location_code),
                  by = c("locations_fuzzy", "admin3_pcode")) 
  

locations %>% filter(str_detect(location, "Monastery"))
```